name: Test memfd

on:
  push:
    paths-ignore:
    - '*.md'
    branches:
    - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  native-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: [nightly, stable, 1.63.0]
    timeout-minutes: 20
    steps:
      - name: Install Rust ${{ matrix.rust_toolchain }}
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          components: clippy
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Update
        run: |
          cargo version
          cargo update
      - name: Clippy
        run: |
          cargo clippy
      - name: Doc
        run: |
          cargo doc
      - name: Build
        run: |
          cargo build
      - name: Test
        run: |
          cargo test -- --nocapture
      - name: Test Release
        run: |
          cargo test --release -- --nocapture

  build-on-unsupported:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    timeout-minutes: 10
    steps:
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537
        with:
          toolchain: nightly
          targets: ${{ matrix.rust_target }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Update
        run: |
          cargo version
          cargo update
      - name: Build ${{ matrix.rust_target }}
        run: |
          cargo build
  cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - arm-linux-androideabi
          - aarch64-linux-android
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Build
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72 # latest
        with:
          use-cross: true
          command: build
          args: --target=${{ matrix.target }} --manifest-path=Cargo.toml
